# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# main:
#   - name: Home
#     url: /
#     weight: 10
# - name: Blog
#   url: blog/
#   weight: 20
# - name: Uses
#   url: uses/
#   weight: 30

main:
  - name: Home
    identifier: Home
    url: https://bobcri005.github.io/Project
    weight: 10

- name: Research
    identifier: Research
    url: /publication/
    weight: 20

  - name: Blog
    identifier: Blog
    url: /blog/
    weight: 30

  - name: Équipe
    identifier: Team
    url: /authors/
    weight: 40

  - name: Contact
    identifier: Contact
    url: /contact/
    weight: 50