# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# main:
#   - name: Home
#     url: /
#     weight: 10
# - name: Blog
#   url: blog/
#   weight: 20
# - name: Uses
#   url: uses/
#   weight: 30

main:
  - name: Home
    identifier: Home
    url: https://bobcri005.github.io/Project
    weight: 10

  - name: Research
    identifier: Research
    url: https://bobcri005.github.io/Project
    weight: 20

  - name: Team
    identifier: Team
    url: https://bobcri005.github.io/Project
    weight: 30

  - name: Publications
    identifier: Publications
    url: https://bobcri005.github.io/Project
    weight: 40

  - name: News
    identifier: News
    url: https://bobcri005.github.io/Project
    weight: 50

  - name: Contact
    identifier: Contact
    url: https://bobcri005.github.io/Project
    weight: 60